describe("Swag Labs", () => {
  it("Purchase 2 prodcuts", async () => {
    await browser.setWindowSize(1366, 768)
    await browser.url("https://www.saucedemo.com/v1/index.html")
    await expect(browser).toHaveUrl("https://www.saucedemo.com/v1/index.html")
    await browser.$("aria/Username").click()
    await browser.$("aria/Username").setValue("standard_user")
    await browser.$("aria/Password").click()
    await browser.$("aria/Password").setValue("secret_sauce")
    await browser.$("#login-button").click()
    await expect(browser).toHaveUrl("https://www.saucedemo.com/v1/inventory.html")
    await browser.$("//*[@id=\"inventory_container\"]/div/div[1]/div[3]/button").click()
    await browser.$("//*[@id=\"inventory_container\"]/div/div[2]/div[3]/button").click()
    await browser.$("aria/2").click()
    await expect(browser).toHaveUrl("https://www.saucedemo.com/v1/cart.html")
    await browser.$("aria/CHECKOUT").click()
    await expect(browser).toHaveUrl("https://www.saucedemo.com/v1/checkout-step-one.html")
    await browser.$("aria/First Name").click()
    await browser.$("aria/First Name").setValue("vamsi")
    await browser.$("aria/Last Name").click()
    await browser.$("aria/Last Name").setValue("krishna")
    await browser.$("aria/Zip/Postal Code").click()
    await browser.$("aria/Zip/Postal Code").setValue("522603")
    await browser.$("//input[@type='submit']").click()
    await expect(browser).toHaveUrl("https://www.saucedemo.com/v1/checkout-step-two.html")
    await browser.$("aria/FINISH").click()
    await expect(browser).toHaveUrl("https://www.saucedemo.com/v1/checkout-complete.html")
  });
});
